# -*- coding: utf-8 -*-
"""Pipeline.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Mutxo-xjgvZjHCkbtdl9lqmeDAfWovdY
"""

import pandas as pd
import numpy as np
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, ConfusionMatrixDisplay
from sklearn.preprocessing import LabelEncoder

# Paso 1: Carga de la fuente de datos
df = pd.read_csv("data/ou_learning_analytics_consolidated.csv")

# LIMPIEZA DE DATOS
df_limpio = df.copy()
# EQUIPO: copia o reconstruye aquí el pipeline de limpieza de S06
# Ejemplo de estructura (adapta a tu dataset):

# Manejo de nulos de la Columna date_registration
# Encontrar el valor mínimo (el negativo más grande, ej. -300). Estos alumnos en su mayoria ha desaprobado y como resultado final del modulo se hna retirado
minimo_registro = df_limpio['date_registration'].min()
df_limpio['date_registration'] = df_limpio['date_registration'].fillna(minimo_registro)


# Manejo de nulos de la columna categorica imd_band
# En esta columna hay algunas celdas que contiene fecha como dia, meas y año. El cual no es un error, solo que se cambio el formato al integrar todas las tablas en una sola
# Por ejemplo si aparece una fecha: 10 de octubre o 20 de octubr es por "10-20"
df_limpio['imd_band'] = df_limpio['imd_band'].replace('10-20', '10-20%')
# Columna imd_band valores faltantes 1111 el cual equivale al 3.41%. Es un valor por debajo del umbral crítico del 5%.
moda_imd_band = df_limpio['imd_band'].mode()[0]
df_limpio['imd_band'] = df_limpio['imd_band'].fillna(moda_imd_band)


# Manejo de nulos de la columna date_unregistration
# En el contexto de la Open University, un valor nulo (NaN) en date_unregistration significa que el estudiante siguió activo y nunca canceló su matrícula. No es un error, es un dato valioso.
# No se puede rellenar con la moda o la media ya que destruiría el significado real del dato

# Al que terminó el curso (Pass, Distinction, Fail) y tiene NaN, le asignamos la duración de su módulo
condicion_completo = (df_limpio['date_unregistration'].isna()) & (df_limpio['final_result'] != 'Withdrawn')
df_limpio.loc[condicion_completo, 'date_unregistration'] = df_limpio['module_presentation_length']

# Si queda algún NaN que sí se retiró (Withdrawn), le ponemos la mediana de días de retiro
mediana_retiro = df_limpio[df_limpio['final_result'] == 'Withdrawn']['date_unregistration'].median()
df_limpio['date_unregistration'] = df_limpio['date_unregistration'].fillna(mediana_retiro)

# CORRECION DE TIPOS DE DATOS
# Convertir las columnas identificadas de tipo float a entero (int)
columnas_enteros = [
    'date_registration',
    'date_unregistration',
    'total_assessments_submitted',
    'total_clicks',
    'unique_days_active'
]
# Convertir las columnas numéricas identificadas a tipo entero
df_limpio[columnas_enteros] = df_limpio[columnas_enteros].astype(int)

# Definir la lista de columnas categóricas para optimizar memoria
columnas_categoricas = [
    'code_module', 'code_presentation', 'gender', 'region',
    'highest_education', 'imd_band', 'age_band', 'disability', 'final_result'
]

# Convertir todas las columnas de la lista a tipo 'category' en un solo paso
df_limpio[columnas_categoricas] = df_limpio[columnas_categoricas].astype('category')

# Recorremos cada columna, limpiamos los espacios, pasamos a minúsculas y aseguramos el formato
for col in columnas_texto:
    df_limpio[col] = (df_ref[col]
                   .astype(str)           # Convertimos temporalmente a texto para poder limpiar
                   .str.strip()           # Eliminamos espacios al inicio y al final
                   .str.lower()           # Pasamos todo a minúsculas
                   .astype('category'))   # Lo devolvemos a tipo 'category' optimizado

# ──────────────────────────────────────────────────────────────
# Transformaciones y variables derivadas
# ──────────────────────────────────────────────────────────────

# EQUIPO: crea las variables derivadas relevantes para tu análisis
# VARIABLE age_band.
# Al plicar uniquezz
df_limpio['age_band'].unique()
# Los resultados son ['0-35', '35-55', '55<='], ademas que la ultima etiqueta esta en orden inverso, el cual es un error
# Definir el nuevo mapeo con las etiquetas corregidas y con mejor significado
mapeo_edades = {
    '0-35': 'menor o igual a 35 años',
    '35-55': 'entre 35 y 55 años',
    '55<=': 'mayor o igual a 55 años'
}

# Renombrar las categorías existentes usando el diccionario
df_limpio['age_band'] = df_limpio['age_band'].cat.rename_categories(mapeo_edades)

# Establecer el orden lógico correcto (Ordinal) para que el modelo entienda la jerarquía y no haya problemas con los modelos de machine learning
orden_edades = ['menor o igual a 35 años', 'entre 35 y 55 años', 'mayor o igual a 55 años']
df_limpio['age_band'] = df_limpio['age_band'].cat.reorder_categories(orden_edades, ordered=True)


# VARIABLES highest_education y imd_band, tienen una escala ordinal (se ordenara explicatamente el orden de menor a mayor), eso sera beneficioso para los algoritmos de machine learning
# Al plicar unique a ambas variables se tiene las siguientes listas
orden_educacion = [
    'no formal quals',
    'lower than a level',
    'a level or equivalent',
    'he qualification',
    'post graduate qualification'
]

orden_imd = [
    '0-10%', '10-20%', '20-30%', '30-40%', '40-50%',
    '50-60%', '60-70%', '70-80%', '80-90%', '90-100%'
]

# Aplicar el tipo categórico ordenado
df_limpio['highest_education'] = df_limpio['highest_education'].cat.reorder_categories(orden_educacion, ordered=True)
df_limpio['imd_band'] = df_limpio['imd_band'].cat.reorder_categories(orden_imd, ordered=True)

# Aplicando submuestreo
from sklearn.utils import resample
df = df_limpio.copy()
# Separar cada clase
pass_df = df[df['final_result'] == 'pass']
withdrawn_df = df[df['final_result'] == 'withdrawn']
fail_df = df[df['final_result'] == 'fail']
distinction_df = df[df['final_result'] == 'distinction']

# Tamaño de la clase minoritaria
n = len(distinction_df)

# Submuestreo de las clases mayoritarias
pass_down = resample(pass_df, replace=False, n_samples=n, random_state=42)

withdrawn_down = resample(withdrawn_df, replace=False, n_samples=n,random_state=42)

fail_down = resample(fail_df, replace=False, n_samples=n, random_state=42)

# Unir todas las clases
df_balanceado = pd.concat([pass_down, withdrawn_down, fail_down, distinction_df])

# Mezclar aleatoriamente el conjunto de datos
df_balanceado = df_balanceado.sample(frac=1, random_state=42).reset_index(drop=True)

# Eliminado columnas que no tiene aporte
df = df_balanceado.drop(columns=[
    'code_module',
    'code_presentation',
    'id_student'
])

# Separar X y Y
X = df.drop(columns='final_result')
y = df['final_result']

# Codificando de variables
# Crear copia del dataset original
df_codificado = df.copy()

# 1. VARIABLES ORDINALES
# age_band
df_codificado['age_band'] = df_codificado['age_band'].map({
    'menor o igual a 35 años': 1,
    'entre 35 y 55 años': 2,
    'mayor o igual a 55 años': 3
})

# highest_education
df_codificado['highest_education'] = df_codificado['highest_education'].map({
    'no formal quals': 1,
    'lower than a level': 2,
    'a level or equivalent': 3,
    'he qualification': 4,
    'post graduate qualification': 5
})

# imd_band
df_codificado['imd_band'] = df_codificado['imd_band'].map({
    '0-10%': 1,
    '10-20%': 2,
    '20-30%': 3,
    '30-40%': 4,
    '40-50%': 5,
    '50-60%': 6,
    '60-70%': 7,
    '70-80%': 8,
    '80-90%': 9,
    '90-100%': 10
})

# 2. VARIABLE BINARIA
df_codificado['disability'] = df_codificado['disability'].map({
    'n': 0,
    'y': 1
})

# 3. VARIABLES NOMINALES
# One Hot Encoding
# drop_first=True evita multicolinealidad
# dtype=int convierte True/False a 1/0

df_codificado = pd.get_dummies(
    df_codificado,
    columns=[
        'gender',
        'region'
    ],
    drop_first=True,
    dtype=int
)

# 4. VARIABLE OBJETIVO
label_encoder = LabelEncoder()
df_codificado['final_result'] = label_encoder.fit_transform(
    df_codificado['final_result']
)

# Eliminar la variable date_unregistration
df_codificado = df_codificado.drop(columns=['date_unregistration'])

# Selección de features con RF feature_importances_ → top-9
from sklearn.ensemble import RandomForestClassifier
import pandas as pd

# Separar variables predictoras y objetivo

X = df_codificado.drop('final_result', axis=1)
y = df_codificado['final_result']


# Lista de nombres de variables predictoras
features_names = X.columns.tolist()

# Convertir a matriz numpy
X_raw = X.values
y_raw = y.values

# Entrenar Random Forest
rf_sel = RandomForestClassifier(
    n_estimators=100,
    random_state=42,
    n_jobs=-1
)
rf_sel.fit(X_raw, y_raw)

# Obtener importancia de variables
importancias = (
    pd.Series(
        rf_sel.feature_importances_,
        index=features_names
    )
    .sort_values(ascending=False)
)

# Seleccionar las 9 variables más importantes
top_features = importancias.head(9).index.tolist()

# Variables dependiente e independientes
X_final = df_codificado[top_features]
y_final = df_codificado['final_result']

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(
    X_final,
    y_final,
    test_size=0.2,  # 20% para el test y 80% para el entrenamiento
    random_state=42,
    stratify=y_final  # Le indica a train_test_split() que mantenga la misma proporción de clases de la variable objetivo (y_final) tanto en el conjunto de entrenamiento como en el de prueba.
)

# Escalar
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# Aplicando regresion logistica
from sklearn.linear_model import LogisticRegression
clf = LogisticRegression(
    max_iter=500,
    random_state=42
)
clf.fit(X_train_scaled, y_train)

y_pred = clf.predict(X_test_scaled)
print(f'Accuracy: {(y_pred == y_test).mean() * 100:.2f} %')

from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))

from sklearn.metrics import confusion_matrix
import pandas as pd

cm = confusion_matrix(y_test, y_pred)

cm_df = pd.DataFrame(
    cm,
    index=clf.classes_,
    columns=clf.classes_
)

cm_df